# Generated by Django 2.1.1 on 2018-10-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('luggage_size', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('release_year', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_address', models.CharField(max_length=50)),
                ('client_brithday', models.DateField()),
                ('client_occupation', models.CharField(max_length=20)),
                ('client_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount_code', models.IntegerField(null=True)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
            ],
            options={
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='DropOffStore',
            fields=[
                ('drop_off_store_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DropOffStore',
            },
        ),
        migrations.CreateModel(
            name='PickUpStore',
            fields=[
                ('pick_up_store_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PickUpStore',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('accident_type', models.CharField(max_length=30)),
                ('accident_address', models.CharField(max_length=30)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.Client')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rent_date', models.DateField()),
                ('end_rent_date', models.DateField()),
                ('rent_price_total', models.IntegerField(null=True)),
                ('pick_up_city', models.CharField(max_length=20)),
                ('drop_off_city', models.CharField(max_length=20)),
                ('insurance_number', models.CharField(max_length=20)),
                ('car_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.Car')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.Client')),
                ('discount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.Discount')),
                ('drop_off_store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.DropOffStore')),
                ('pick_up_store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.PickUpStore')),
            ],
            options={
                'db_table': 'Rental',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30)),
                ('store_address', models.CharField(max_length=30)),
                ('store_phone', models.TextField(default='null')),
                ('store_city', models.CharField(max_length=30)),
                ('store_state_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.AddField(
            model_name='pickupstore',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.Store'),
        ),
        migrations.AddField(
            model_name='dropoffstore',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.Store'),
        ),
        migrations.AddField(
            model_name='car',
            name='record_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_car.Record'),
        ),
    ]
