# Generated by Django 2.1.1 on 2018-10-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
