# Generated by Django 2.1.1 on 2018-10-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(choices=[('LAND ROVER', 'LAND ROVER'), ('BMW', 'BMW'), ('VOLVO', 'VOLVO'), ('VOLKSWAGEN', 'VOLKSWAGEN'), ('TOYOTA', 'TOYOTA'), ('SAAB', 'SAAB'), ('RENAULT', 'RENAULT'), ('NISSAN', 'NISSAN'), ('MITSUBISHI', 'MITSUBISHI'), ('MERCEDES-BENZ', 'MERCEDES-BENZ'), ('MAZDA', 'MAZDA'), ('HONDA', 'HONDA'), ('EUNOS', 'EUNOS'), ('DATSUN', 'DATSUN'), ('CHRYSLER', 'CHRYSLER'), ('AUDI', 'AUDI'), ('ALFA ROMEO', 'ALFA ROMEO'), ('PEUGEOT', 'PEUGEOT'), ('NULL', 'NULL')], max_length=13)),
                ('type', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('luggage_size', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('release_year', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_address', models.CharField(max_length=50)),
                ('client_brithday', models.DateField()),
                ('client_occupation', models.CharField(max_length=20)),
                ('client_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount_code', models.IntegerField(null=True)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
            ],
            options={
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='DropOffStore',
            fields=[
                ('drop_off_store_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DropOffStore',
            },
        ),
        migrations.CreateModel(
            name='PickUpStore',
            fields=[
                ('pick_up_store_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PickUpStore',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('accident_type', models.CharField(max_length=30)),
                ('accident_address', models.CharField(max_length=30)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.Client')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rent_date', models.DateField()),
                ('end_rent_date', models.DateField()),
                ('rent_price_total', models.IntegerField(null=True)),
                ('pick_up_city', models.CharField(choices=[('Sydney', 'Sydney'), ('Melbourne', 'Melbourne'), ('Brisbane', 'Brisbane')], max_length=9)),
                ('drop_off_city', models.CharField(choices=[('Sydney', 'Sydney'), ('Melbourne', 'Melbourne'), ('Brisbane', 'Brisbane')], max_length=9)),
                ('insurance_number', models.CharField(max_length=20)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.Car')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.Client')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.Discount')),
                ('drop_off_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.DropOffStore')),
                ('pick_up_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.PickUpStore')),
            ],
            options={
                'db_table': 'Rental',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30)),
                ('store_address', models.CharField(max_length=30)),
                ('store_phone', models.TextField(default='null')),
                ('store_city', models.CharField(max_length=30)),
                ('store_state_name', models.CharField(choices=[('Queensland', 'Queensland'), ('South Australia', 'South Australia'), ('Tasmania', 'Tasmania'), ('Victoria', 'Victoria'), ('New South Wales', 'New South Wales')], max_length=15)),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.AddField(
            model_name='pickupstore',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.Store'),
        ),
        migrations.AddField(
            model_name='dropoffstore',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.Store'),
        ),
        migrations.AddField(
            model_name='car',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarApp.Record'),
        ),
    ]
